--[[
	permission_users.lua
	
	Distributed as Public Domain, with no license.
	This file was generated by a script.
--]]

return {
    hearnsb = {
        group = "admin",
        lastgroup = "admin"
}
}